--(string, varable, varable, varable, string_format, imgui_flags)
imgui.InputDouble(name, value, step, step_fast, ¿format, ¿flags)
--(string, varable, varable, varable, string_format, imgui_flags)
imgui.InputFloat(name, value, step, faststep, ¿format, ¿flags)
--(string, varable, varable, varable, string_format, imgui_flags)
imgui.InputIntname, value, step, faststep, ¿format, ¿flags)
--(string, varable, imgui_flags)
imgui.InputText(name, value, ¿flags)
--(string, varable, numberic, {x, y}, imgui_flags)
imgui.InputTextMultiline(name, value, length, size, ¿flags)
--(string, imgui_data, numeric?, numeric?, string_format, imgui_flags)
imgui.InputTextScaler(name, data_type, ¿?step, ¿?step_fast, ¿format, ¿flags)
--(string, string, varable, numeric, imgui_flags)
imgui.InputTextWithHint(name, hint, value, length, ¿flags)
