--[=[ ImFontPtr, ushort, int, int, float ]=]
ImGuiFontAtlasPtr.AddCustomRectFontGlyph(font, id, width, height, advance_x) [=[ int ]=]
--[=[ ImFontPtr, ushort, int, int, float, Vector2 ]=]
ImGuiFontAtlasPtr.AddCustomRectFontGlyph(font, id, width, height, advance_x, offset) [=[ int ]=]
--[=[ int, int ]=]
ImGuiFontAtlasPtr.AddCustomRectRegular(width, height) [=[ int ]=]
--[=[ ImFontConfigPtr ]=]
ImGuiFontAtlasPtr.AddFont(font_cfg) [=[ ImFontPtr ]=]
--[=[ ImFontConfigPtr ]=]
ImGuiFontAtlasPtr.AddFontDefault(font_cfg) [=[ ImFontPtr ]=]
ImGuiFontAtlasPtr.AddFontDefault() [=[ ImFontPtr ]=]
--[=[ ReadOnlySpan<char>, float, ImFontConfigPtr, IntPtr ]=]
ImGuiFontAtlasPtr.AddFontFromFileTTF(filename, size_pixels, font_cfg, glyph_ranges) [=[ ImFontPtr ]=]
--[=[ string, float, ImFontConfigPtr, IntPtr ]=]
ImGuiFontAtlasPtr.AddFontFromFileTTF(filename, size_pixels, font_cfg, glyph_ranges) [=[ ImFontPtr ]=]
--[=[ string, float, ImFontConfigPtr ]=]
ImGuiFontAtlasPtr.AddFontFromFileTTF(filename, size_pixels, font_cfg) [=[ ImFontPtr ]=]
--[=[ string, float ]=]
ImGuiFontAtlasPtr.AddFontFromFileTTF(filename, size_pixels) [=[ ImFontPtr ]=]
--[=[ ReadOnlySpan<char>, float ]=]
ImGuiFontAtlasPtr.AddFontFromFileTTF(filename, size_pixels) [=[ ImFontPtr ]=]
--[=[ ReadOnlySpan<char>, float, ImFontConfigPtr ]=]
ImGuiFontAtlasPtr.AddFontFromFileTTF(filename, size_pixels, font_cfg) [=[ ImFontPtr ]=]
--[=[ string, float, ImFontConfigPtr ]=]
ImGuiFontAtlasPtr.AddFontFromMemoryCompressedBase85TTF(compressed_font_data_base85, size_pixels, font_cfg) [=[ ImFontPtr ]=]
--[=[ ReadOnlySpan<char>, float, ImFontConfigPtr ]=]
ImGuiFontAtlasPtr.AddFontFromMemoryCompressedBase85TTF(compressed_font_data_base85, size_pixels, font_cfg) [=[ ImFontPtr ]=]
--[=[ ReadOnlySpan<char>, float, ImFontConfigPtr, IntPtr ]=]
ImGuiFontAtlasPtr.AddFontFromMemoryCompressedBase85TTF(compressed_font_data_base85, size_pixels, font_cfg, glyph_ranges) [=[ ImFontPtr ]=]
--[=[ string, float ]=]
ImGuiFontAtlasPtr.AddFontFromMemoryCompressedBase85TTF(compressed_font_data_base85, size_pixels) [=[ ImFontPtr ]=]
--[=[ ReadOnlySpan<char>, float ]=]
ImGuiFontAtlasPtr.AddFontFromMemoryCompressedBase85TTF(compressed_font_data_base85, size_pixels) [=[ ImFontPtr ]=]
--[=[ string, float, ImFontConfigPtr, IntPtr ]=]
ImGuiFontAtlasPtr.AddFontFromMemoryCompressedBase85TTF(compressed_font_data_base85, size_pixels, font_cfg, glyph_ranges) [=[ ImFontPtr ]=]
--[=[ IntPtr, int, float, ImFontConfigPtr, IntPtr ]=]
ImGuiFontAtlasPtr.AddFontFromMemoryCompressedTTF(compressed_font_data, compressed_font_data_size, size_pixels, font_cfg, glyph_ranges) [=[ ImFontPtr ]=]
--[=[ IntPtr, int, float, ImFontConfigPtr ]=]
ImGuiFontAtlasPtr.AddFontFromMemoryCompressedTTF(compressed_font_data, compressed_font_data_size, size_pixels, font_cfg) [=[ ImFontPtr ]=]
--[=[ IntPtr, int, float ]=]
ImGuiFontAtlasPtr.AddFontFromMemoryCompressedTTF(compressed_font_data, compressed_font_data_size, size_pixels) [=[ ImFontPtr ]=]
--[=[ IntPtr, int, float, ImFontConfigPtr ]=]
ImGuiFontAtlasPtr.AddFontFromMemoryTTF(font_data, font_data_size, size_pixels, font_cfg) [=[ ImFontPtr ]=]
--[=[ IntPtr, int, float, ImFontConfigPtr, IntPtr ]=]
ImGuiFontAtlasPtr.AddFontFromMemoryTTF(font_data, font_data_size, size_pixels, font_cfg, glyph_ranges) [=[ ImFontPtr ]=]
--[=[ IntPtr, int, float ]=]
ImGuiFontAtlasPtr.AddFontFromMemoryTTF(font_data, font_data_size, size_pixels) [=[ ImFontPtr ]=]
ImGuiFontAtlasPtr.Build() [=[ bool ]=]
--[=[ ImFontAtlasCustomRectPtr, out Vector2, out Vector2 ]=]
ImGuiFontAtlasPtr.CalcCustomRectUV(rect, out_uv_min, out_uv_max) [=[  ]=]
ImGuiFontAtlasPtr.Clear() [=[  ]=]
ImGuiFontAtlasPtr.ClearFonts() [=[  ]=]
ImGuiFontAtlasPtr.ClearInputData() [=[  ]=]
ImGuiFontAtlasPtr.ClearTexData() [=[  ]=]
ImGuiFontAtlasPtr.ConfigData [=[ ImPtrVector<ImFontConfigPtr> ]=]
ImGuiFontAtlasPtr.CustomRects [=[ ImPtrVector<ImFontAtlasCustomRectPtr> ]=]
ImGuiFontAtlasPtr.Destroy() [=[  ]=]
ImGuiFontAtlasPtr.Flags [=[ ref ImFontAtlasFlags ]=]
ImGuiFontAtlasPtr.FontBuilderFlags [=[ ref uint ]=]
ImGuiFontAtlasPtr.FontBuilderIO [=[ IntPtr ]=]
ImGuiFontAtlasPtr.Fonts [=[ ImVector<ImFontPtr> ]=]
--[=[ int ]=]
ImGuiFontAtlasPtr.GetCustomRectByIndex(index) [=[ ImFontAtlasCustomRectPtr ]=]
ImGuiFontAtlasPtr.GetGlyphRangesChineseFull() [=[ IntPtr ]=]
ImGuiFontAtlasPtr.GetGlyphRangesChineseSimplifiedCommon() [=[ IntPtr ]=]
ImGuiFontAtlasPtr.GetGlyphRangesCyrillic() [=[ IntPtr ]=]
ImGuiFontAtlasPtr.GetGlyphRangesDefault() [=[ IntPtr ]=]
ImGuiFontAtlasPtr.GetGlyphRangesGreek() [=[ IntPtr ]=]
ImGuiFontAtlasPtr.GetGlyphRangesJapanese() [=[ IntPtr ]=]
ImGuiFontAtlasPtr.GetGlyphRangesKorean() [=[ IntPtr ]=]
ImGuiFontAtlasPtr.GetGlyphRangesThai() [=[ IntPtr ]=]
ImGuiFontAtlasPtr.GetGlyphRangesVietnamese() [=[ IntPtr ]=]
--[=[ ImGuiMouseCursor, out Vector2, out Vector2, out Vector2, out Vector2 ]=]
ImGuiFontAtlasPtr.GetMouseCursorTexData(cursor, out_offset, out_size, out_uv_border, out_uv_fill) [=[ bool ]=]
--[=[ out IntPtr, out int, out int ]=]
ImGuiFontAtlasPtr.GetTexDataAsAlpha8(out_pixels, out_width, out_height) [=[  ]=]
--[=[ out byte*, out int, out int ]=]
ImGuiFontAtlasPtr.GetTexDataAsAlpha8(out_pixels, out_width, out_height) [=[  ]=]
--[=[ out byte*, out int, out int, out int ]=]
ImGuiFontAtlasPtr.GetTexDataAsAlpha8(out_pixels, out_width, out_height, out_bytes_per_pixel) [=[  ]=]
--[=[ out IntPtr, out int, out int, out int ]=]
ImGuiFontAtlasPtr.GetTexDataAsAlpha8(out_pixels, out_width, out_height, out_bytes_per_pixel) [=[  ]=]
--[=[ out IntPtr, out int, out int ]=]
ImGuiFontAtlasPtr.GetTexDataAsRGBA32(out_pixels, out_width, out_height) [=[  ]=]
--[=[ out IntPtr, out int, out int, out int ]=]
ImGuiFontAtlasPtr.GetTexDataAsRGBA32(out_pixels, out_width, out_height, out_bytes_per_pixel) [=[  ]=]
--[=[ out byte*, out int, out int, out int ]=]
ImGuiFontAtlasPtr.GetTexDataAsRGBA32(out_pixels, out_width, out_height, out_bytes_per_pixel) [=[  ]=]
--[=[ out byte*, out int, out int ]=]
ImGuiFontAtlasPtr.GetTexDataAsRGBA32(out_pixels, out_width, out_height) [=[  ]=]
ImGuiFontAtlasPtr.IsBuilt() [=[ bool ]=]
ImGuiFontAtlasPtr.Locked [=[ ref bool ]=]
ImGuiFontAtlasPtr.NativePtr [=[ ImFontAtlas* ]=]
ImGuiFontAtlasPtr.PackIdLines [=[ ref int ]=]
ImGuiFontAtlasPtr.PackIdMouseCursors [=[ ref int ]=]
--[=[ IntPtr ]=]
ImGuiFontAtlasPtr.SetTexID(id) [=[  ]=]
ImGuiFontAtlasPtr.TexDesiredWidth [=[ ref int ]=]
ImGuiFontAtlasPtr.TexGlyphPadding [=[ ref int ]=]
ImGuiFontAtlasPtr.TexHeight [=[ ref int ]=]
ImGuiFontAtlasPtr.TexID [=[ ref IntPtr ]=]
ImGuiFontAtlasPtr.TexPixelsAlpha8 [=[ IntPtr ]=]
ImGuiFontAtlasPtr.TexPixelsRGBA32 [=[ IntPtr ]=]
ImGuiFontAtlasPtr.TexPixelsUseColors [=[ ref bool ]=]
ImGuiFontAtlasPtr.TexReady [=[ ref bool ]=]
ImGuiFontAtlasPtr.TexUvLines [=[ RangeAccessor<Vector4> ]=]
ImGuiFontAtlasPtr.TexUvScale [=[ ref Vector2 ]=]
ImGuiFontAtlasPtr.TexUvWhitePixel [=[ ref Vector2 ]=]
ImGuiFontAtlasPtr.TexWidth [=[ ref int ]=]
ImGuiFontAtlasPtr.UserData [=[ IntPtr ]=]